CONFIG

  ENV
    # don’t allow arbitrary map path loading
    #MS_MAP_NO_PATH "true"                          
    # only allow map files in this directory
    #MS_MAP_PATTERN "^/var/www/html/htdocs/serverGIS/mapserver/mapfiles/.*\.map$"
    MS_MAP_PATTERN "^/var/www/html/htdocs/.*\.map$"
    # default debug verbosity
    MS_DEBUGLEVEL "2"
    #MS_VERBOSE "false"
    # Log file
    MS_ERRORFILE "/var/log/mapserver/mapserver_errors.log"
  END


  #
  # Map aliases:
  # if MS_MAP_NO_PATH "true" then the map is ONLY accessed via:
  # http://localhost/cgi-bin/mapserv?map=MAIN
  # where MAIN is the name of the alias.
  # Otherwise it accessible with or without alias
  MAPS
    MAIN                   "/var/www/html/htdocs/serverGIS/mapserver/mapfiles/hello.map"
    CANADA_COLOR           "/var/www/html/htdocs/serverGIS/mapserver/mapfiles/canada_color.map"
    CANADA_COLOR_WEB       "/var/www/html/htdocs/serverGIS/mapserver/mapfiles/canada_color_web.map"
    CANADA_COLOR_WEB_WMTS  "/var/www/html/htdocs/serverGIS/mapserver/mapfiles/canada_color_web_wmts.map"
  END

	ENV
		GDAL_NUM_THREADS '12' #"ALL_CPUS"
		GDAL_CACHEMAX "4096"
	END

END
